In [1]:
import pandas as pd
import numpy as np
import pickle

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
df = pd.read_csv("waterQuality.csv")

In [3]:
df.head()

,aluminium,ammonia,arsenic,barium,cadmium,chloramine,chromium,copper,flouride,bacteria,...,lead,nitrates,nitrites,mercury,perchlorate,radium,selenium,silver,uranium,is_safe
0,1.65,9.08,0.04,2.85,0.007,0.35,0.83,0.17,0.05,0.20,...,0.054,16.08,1.13,0.007,37.75,6.78,0.08,0.34,0.02,1
1,2.32,21.16,0.01,3.31,0.002,5.28,0.68,0.66,0.90,0.65,...,0.100,2.01,1.93,0.003,32.26,3.21,0.08,0.27,0.05,1
2,1.01,14.02,0.04,0.58,0.008,4.24,0.53,0.02,0.99,0.05,...,0.078,14.16,1.11,0.006,50.28,7.07,0.07,0.44,0.01,0
3,1.36,11.33,0.04,2.96,0.001,7.23,0.03,1.66,1.08,0.71,...,0.016,1.41,1.29,0.004,9.12,1.72,0.02,0.45,0.05,1
4,0.92,24.33,0.03,0.20,0.006,2.67,0.69,0.57,0.61,0.13,...,0.117,6.74,1.11,0.003,16.90,2.41,0.02,0.06,0.02,1

In [4]:
df.isnull().sum()

aluminium      0
ammonia        0
arsenic        0
barium         0
cadmium        0
chloramine     0
chromium       0
copper         0
flouride       0
bacteria       0
viruses        0
lead           0
nitrates       0
nitrites       0
mercury        0
perchlorate    0
radium         0
selenium       0
silver         0
uranium        0
is_safe        0
dtype: int64

In [5]:
df.fillna(df.select_dtypes(include=np.number).mean(), inplace=True)

In [6]:
df.isnull().sum()

aluminium      0
ammonia        0
arsenic        0
barium         0
cadmium        0
chloramine     0
chromium       0
copper         0
flouride       0
bacteria       0
viruses        0
lead           0
nitrates       0
nitrites       0
mercury        0
perchlorate    0
radium         0
selenium       0
silver         0
uranium        0
is_safe        0
dtype: int64

In [7]:
df = df[df['is_safe'] != '#NUM!']

In [8]:
df['is_safe'] = df['is_safe'].astype(int)

In [9]:
df['is_safe'].value_counts()

is_safe
0    7084
1     912
Name: count, dtype: int64

In [10]:
features = [
    'aluminium',
    'arsenic',
    'barium',
    'cadmium',
    'chloramine',
    'chromium',
    'viruses',
    'nitrates',
    'radium',
    'silver'
]

X = df[features]
y = df['is_safe']

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [12]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [13]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train_scaled, y_train)

RandomForestClassifier(random_state=42)

In [14]:
y_pred = rf.predict(X_test_scaled)

In [15]:
from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.915

In [16]:
safe_sample = [[
    0.08,
    0.005,
    0.4,
    0.002,
    3,
    0.02,
    0,
    5,
    1,
    0.01
]]

safe_scaled = scaler.transform(safe_sample)

print(rf.predict(safe_scaled))

[1]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [17]:
unsafe_sample = [[
    2.5,
    0.08,
    3.5,
    0.04,
    11,
    0.09,
    1,
    28,
    8,
    0.1
]]

unsafe_scaled = scaler.transform(unsafe_sample)

print(rf.predict(unsafe_scaled))

[0]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [18]:
import pickle

pickle.dump(rf, open("model.pkl", "wb"))
pickle.dump(scaler, open("scaler.pkl", "wb"))

print("Model saved successfully!")

Model saved successfully!

In [19]:
safe_sample = [[
    0.08,
    0.005,
    0.4,
    0.002,
    3,
    0.02,
    0,
    5,
    1,
    0.01
]]

safe_scaled = scaler.transform(safe_sample)

print("Safe Prediction:", rf.predict(safe_scaled))

Safe Prediction: [1]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [20]:
unsafe_sample = [[
    2.5,
    0.08,
    3.5,
    0.04,
    11,
    0.09,
    1,
    28,
    8,
    0.1
]]

unsafe_scaled = scaler.transform(unsafe_sample)

print("Unsafe Prediction:", rf.predict(unsafe_scaled))

Unsafe Prediction: [0]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [24]:
safe_sample = [[
    1.12,
    0.03,
    2.40,
    0.004,
    1.20,
    0.62,
    0.120,
    8.50,
    2.10,
    0.15
]]

safe_scaled = scaler.transform(safe_sample)

print("Safe Prediction:", rf.predict(safe_scaled))


unsafe_sample = [[
    3.85,
    0.04,
    2.95,
    0.008,
    6.90,
    0.21,
    0.820,
    15.80,
    7.35,
    0.41
]]

unsafe_scaled = scaler.transform(unsafe_sample)

print("Unsafe Prediction:", rf.predict(unsafe_scaled))

Safe Prediction: [1]
Unsafe Prediction: [0]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [21]:
safe_rows = df[df['is_safe'] == 1]

safe_rows[features].head(10)

,aluminium,arsenic,barium,cadmium,chloramine,chromium,viruses,nitrates,radium,silver
0,1.65,0.04,2.85,0.007,0.35,0.83,0.000,16.08,6.78,0.34
1,2.32,0.01,3.31,0.002,5.28,0.68,0.650,2.01,3.21,0.27
3,1.36,0.04,2.96,0.001,7.23,0.03,0.710,1.41,1.72,0.45
4,0.92,0.03,0.20,0.006,2.67,0.69,0.001,6.74,2.41,0.06
5,0.94,0.03,2.88,0.003,0.80,0.43,0.670,9.75,5.42,0.19
8,0.60,0.01,0.71,0.005,3.14,0.77,0.002,14.66,4.99,0.25
9,0.22,0.02,1.37,0.007,6.40,0.49,0.830,4.79,0.08,0.31
11,1.35,0.04,0.84,0.002,0.10,0.76,0.520,18.40,1.30,0.48
12,1.88,0.02,2.78,0.008,0.05,0.42,0.910,4.37,1.97,0.06
13,4.93,0.04,3.05,0.008,0.70,0.51,0.700,1.16,5.58,0.38

In [22]:
unsafe_rows = df[df['is_safe'] == 0]

unsafe_rows[features].head(10)

,aluminium,arsenic,barium,cadmium,chloramine,chromium,viruses,nitrates,radium,silver
2,1.01,0.040,0.58,0.008,4.24,0.53,0.003,14.16,7.07,0.44
6,2.36,0.010,1.35,0.004,1.28,0.62,0.007,18.60,2.84,0.24
7,3.93,0.040,0.66,0.001,6.22,0.10,0.005,13.65,7.24,0.08
10,3.27,0.001,2.69,0.005,5.75,0.15,0.008,8.47,7.80,0.33
18,4.88,0.020,0.36,0.001,1.21,0.68,0.750,0.31,1.00,0.41
23,4.32,0.030,2.60,0.008,7.24,0.61,0.560,9.42,3.22,0.18
24,2.36,0.010,0.68,0.003,4.07,0.13,0.960,15.05,7.99,0.50
27,3.42,0.001,2.80,0.003,2.87,0.73,0.002,13.73,3.29,0.17
29,4.57,0.010,3.04,0.002,2.78,0.72,0.006,9.64,4.55,0.19
33,1.63,0.030,2.54,0.008,4.25,0.74,0.006,17.29,1.71,0.44